# 延迟刷入磁盘的时间，因为我们没往外挂载，所以压根不重要
# 间隔提高可以减少磁盘负载
filebeat.registry.flush: 5s
# 停止延迟时间
filebeat.shutdown_timeout: 5s
# 输入配置
filebeat.inputs:
  - type: log
    processors:
      # 配置添加字段标识使用的日志格式和服务名
      - add_fields:
          fields:
            log_type: frame_log
            service: swagger2word
    enabled: true
    paths:
      - /app/logs/*.log
    # 解析方案：此处为通过行首的日期格式区分
    multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}'
    multiline.negate: true
    multiline.match: after
# 一般的输出到es
#output.elasticsearch:
#  hosts: ["127.0.0.1:9200"]
#  username: "elastic"
#  password: "eeexxxsss"
#  pipelines:
#    - pipeline: "%{[fields.log_type]}"
#      mappings:
#        frame_log: "frame_log_test"
# 测试用的输出到文件
output.file:
  path: "/tmp/filebeat"
  filename: filebeat
